[package]
name = "nextgen"
version = "0.1.0"
authors = ["Florian Anderiasch <fa@art-core.org>"]
edition = "2018"

[dependencies]
pulldown-cmark = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.5"
walkdir = "2"

[dependencies.tera]
version = "1"
default-features = false
