[package]
name = "nextgen"
version = "0.1.0"
authors = ["Florian Anderiasch <fa@art-core.org>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
pulldown-cmark = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
walkdir = "2"

[dependencies.tera]
version = "1"
default-features = false
